pool:
  vmImage: 'Ubuntu 16.04'
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Bash@1
  displayName: 'compile'
  inputs:
    script: npm run build
